### ISSUE TITLE
系统无法接受输入的日期.... 

### ISSUE THREAD

**Issue by psdshow** [DeepSkyFire/XShell5-Startup-Script#1]
脚本里面的时间格式是错误的 
我改成这样就可以了 2018-12-25

**Comment by DeepSkyFire** [comment]
關於時間格式的説明：

因各個系統的默認時間格式不一樣，所以“25-12-2018”這個格式的時間可能在其他系統上無法使用。

例如簡中系統的默認時間格式為“2018-12-25”，所以脚本内的時間格式要改爲此才能正常使用。

本脚本的時間格式為繁中系統默認格式，所以繁中系統上可正常使用。
